### ISSUE TITLE
Version of 0.* results in empty semver major value

### ISSUE THREAD

**Issue by swichers** [battila7/get-version-action#15]
When tagging with a version like `0.1` the major value will not be set.

Simple example:

```yml
      - name: Get latest release version number
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Debug
        run: echo 'Major version: ${{ steps.get_version.outputs.major }}'
```

Result:

```
Major version: 
```

Expected:

```
Major version: 0
```

If this is working as intended then an update to the README would be great. This burned some time.
